## Numpy Documantation

✅ What is astype() in NumPy?

astype() is a method used to convert (cast) the data type of a NumPy array to another type.

✔ It returns a new array

✔ It does NOT change the original array

✔ Used for type conversion: int ↔ float ↔ string ↔ bool, etc.


In [ ]:
import numpy as np

In [ ]:
# Type conversion in Numpy

import numpy as np

arr = np.array([1,2,3,4], dtype=np.float32)
print(arr, arr.dtype)  # [1. 2. 3. 4.] float32

# another example

arr_float = np.array([1.1, 2.5, 3.9] , dtype=np.float64)
arr_int = arr_float.astype(int)
print(arr_int)  # [1 2 3]
print(arr_int.dtype)  # int32 (system dependent)


# float ----> boolean

arr = np.array([0.0, 1.5, -2.3])
arr_bool = arr.astype(bool)
print(arr_bool)  # [False True True]


# Boolean → Integer / Float
arr = np.array([True, False, True])
arr_int = arr.astype(int)
arr_float = arr.astype(float)
print(arr_int)    # [1 0 1]
print(arr_float)  # [1. 0. 1.]

# Integer → Float

arr = np.array([1,2,3])
arr_float = arr.astype(float)
print(arr_float)  # [1. 2. 3.]
print(arr_float.dtype)  # float64


** Important Notes**

1.  astype() always returns a new array
2.  Conversion may truncate or round values: float → int




1.   Conversion may truncate or round values: float → int
2.  Memory usage depends on dtype:
    float32 → 4 bytes per element
    float64 → 8 bytes per element







In [ ]:
# 🌐 NumPy Random Arrays – Detailed Explanation

r = np.random.rand(2,2)
print(r)
r_int = r.astype(int)
print(r_int)
print(r.mean())
print(r.std())
print(r.var())

Standard Normal Distribution (randn)

In [ ]:
r = np.random.randn(4)
print(r)

# np.random.randn() → standard normal distribution      ****(mean=0, std=1)****
# Can specify shape: np.random.randn(2,3) → 2×3 array
# Useful in statistical simulations

[ 0.11915583 -0.66567969 -1.60771439  0.17668141]


Random Integers (randint)

## 4️⃣ Random Choice (choice):


| Goal                  | Code                                         |
| --------------------- | -------------------------------------------- |
| Pick 1 random item    | `np.random.choice(a)`                        |
| Pick n items          | `np.random.choice(a, size=n)`                |
| Pick unique items     | `np.random.choice(a, size=n, replace=False)` |
| Weighted sampling     | `np.random.choice(a, size=n, p=probs)`       |
| Sample integers 0→N-1 | `np.random.choice(N, size=n)`                |


In [ ]:
# The basic syntax of the np.random.choice
# np.random.choice(a, size=None, replace=True, p=None)
# | Parameter   | Meaning                                             |
# | ----------- | --------------------------------------------------- |
# | **a**       | The data to sample from (list, array, or integer N) |
# | **size**    | Number of samples returned                          |
# | **replace** | Allow picking the same item multiple times?         |
# | **p**       | Probability distribution (must sum to 1)            |
import numpy as np
arr = np.random.choice([10,20,30,40], size=7)
print(arr)

fruits = np.random.choice(
    ['apple','banana','mango'],
    size=5,
    p=[0.1, 0.7, 0.2]    # p = probabilities
)  #banana has more probability so it mostly banana will occur in random choice
print(fruits)

#2D Output (size as tuple)
arr_2d = np.random.choice(10, size=(2,3))
print(arr_2d)


coin = np.random.choice(['H','T'], size=1000, p=[0.5,0.5])
print(coin)
# arr_2d = np.randam.choice([10,20,30,40], size=(2,3))
# print(arr_2d)

# np.random.choice()

# Randomly picks elements from given array or list

# Can add replace=False → no repetition

# Can specify weights for probability distribution

5️⃣ Seeding the Random Generator

In [10]:
np.random.seed(12)
r = np.random.rand(4)
print(r)



# seed() → makes random numbers reproducible

# Useful for debugging / experiments

# Example Output: (same every time)

[0.15416284 0.7400497  0.26331502 0.53373939]


## Standard Normal Distribution
np.random.randn
## Gaussian Distribution


In [ ]:
x = np.random.randn(1_000_000)
print(np.mean(x))


6️⃣ Summary Table

| Function              | Output            | Example Shape | Range / Notes                   |
| --------------------- | ----------------- | ------------- | ------------------------------- |
| `np.random.rand()`    | float array       | `(3,3)`       | [0,1) uniform                   |
| `np.random.randn()`   | float array       | `(2,4)`       | standard normal (mean=0, std=1) |
| `np.random.randint()` | int array         | `(2,3)`       | [low, high)                     |
| `np.random.choice()`  | selected elements | `(5,)`        | from array/list, optional prob  |


In [ ]:
r_int = np.random.randint(1,10,(2,3))
print(r_int)

# Explanation:

# np.random.randint(low, high, size)

# low → inclusive

# high → exclusive

# size → shape of array

# Generates integers

# Useful for random indexing, test data

##np.linspace in NumPy

Definition

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Generates num evenly spaced numbers between start and stop.

Returns an array of floats (by default).


| Parameter  | Meaning                                                        |
| ---------- | -------------------------------------------------------------- |
| `start`    | The starting value of the sequence                             |
| `stop`     | The end value of the sequence                                  |
| `num`      | How many numbers to generate (default 50)                      |
| `endpoint` | If True (default), `stop` is included; if False, it’s excluded |
| `retstep`  | If True, also return the **step size** between numbers         |
| `dtype`    | Type of the output array (optional)                            |


In [ ]:
import numpy as np

arr = np.linspace(0, 10, 5, endpoint=True, retstep=True)
print(arr)



In [ ]:
import numpy as np

a = np.array([1, 2, 4, 8])          # default integer
b = np.array([1.5, 2.5, 3.5, 4.5])    # default float
c = np.array([1+2j, 3+4j])       # complex
d = np.array([True, False, True])# boolean

vector = np.array([1,2,3])
matrix = np.array([[2,4],[6,7]])
tensor = np.array([[[5,3],[4,8]],[[4,1],[5,9]]])

print(a,b,c,d)
print(a.dtype,b.dtype,c.dtype,d.dtype)
print("vector \n ", vector)
print("matrix \n ",matrix)
print("Tensor \n ",tensor)

# reshaped
reshaped = a.reshape((2,2))
print(reshaped)
print(reshaped.T)

# addition

sum = a + b
print(sum)


# Default matrices

zero_matrix = np.zeros((5,6))    #Null matrix
oness_matrix = np.ones((50,50))
identity_matrix = np.eye(4)          #Identity matrix
const_matrix = np.full((2,3),5)
print(zero_matrix)
print(oness_matrix)
print(identity_matrix)
print(const_matrix)

print(zero_matrix.shape)
print(oness_matrix.shape)
print(identity_matrix.shape)
print(const_matrix.shape)

print(zero_matrix.dtype)
print(oness_matrix.dtype)
print(identity_matrix.dtype)
print(const_matrix.dtype)

print(zero_matrix.ndim)
print(oness_matrix.ndim)
print(identity_matrix.ndim)
print(const_matrix.ndim)

print(zero_matrix.size)
print(oness_matrix.size)
print(identity_matrix.size)
print(const_matrix.size)

print(zero_matrix.itemsize)
print(oness_matrix.itemsize)
print(identity_matrix.itemsize)
print(const_matrix.itemsize)

print(zero_matrix.nbytes)
print(oness_matrix.nbytes)
print(identity_matrix.nbytes)
print(const_matrix.nbytes)

print(zero_matrix.T)
print(oness_matrix.T)
print(identity_matrix.T)
print(const_matrix.T)

*Quick Review Table*

Attribute	What It Tells You

shape : 	Size in each dimension

ndim :	Number of dimensions

size :	Total number of elements

itemsize  : 	Bytes per element

nbytes	: Total bytes used

In [ ]:
#let's play with complex numbers

complex_number = 2 + 3j
print(complex_number)

c = np.array([1+2j, 3+4j, 5+6j])
print(c)
print(c.dtype)
print(c.real)
print(c.imag)

a = c.real
b = c.imag

real_imag_Matrix = np.array([a,b])
print(real_imag_Matrix)
print(real_imag_Matrix.shape)
print(real_imag_Matrix.ndim)
print(real_imag_Matrix.size)
print(real_imag_Matrix.itemsize)
print(real_imag_Matrix.nbytes)

for x in real_imag_Matrix.flat:
  print(x , end="")

Key Differences:

## flatten() vs ravel()

## *flatten()*

->  Always returns a new one-dimensional copy of the data.

->  Slower because it copies memory.

->  Changes made to the result do not affect the original array.


## *ravel()*

->  Tries to return a view; only makes a copy if necessary (for example, with non-contiguous data).

->  Faster and uses less memory.

->  Changes to the view reflect in the original array (if it's a view).

Quick Table
Function  	Returns 	Link to original  	Speed

flatten()	  Copy	    No	                Slower

ravel()	    View (if possible)    	Yes (if view)	     Faster



In [ ]:
zero_matrix = np.array([1, 2, 4, 8])
a = zero_matrix.reshape((2,2))
b = zero_matrix.flatten()
c = zero_matrix.ravel()

print(zero_matrix)
print(a)
print(b)
print(c)

In [ ]:
# lets slice the matrix and enjoy the mathematical things viva code

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0, 0])  # First row, first column → 10
print(arr[1, 2])  # Second row, third column → 60
print(arr[-1, -1])# Last row, last column → 90

print(arr[1, :])  # Second row → [40 50 60]
print(arr[:, 2])  # Third column → [30 60 90]

# lets perform slcing method on the array

v = np.array([10,20,30,40,50,60])

print(v[1:5])     # elements 1 to 4 → [20 30 40 50]
print(v[:4])      # from start to 3 → [10 20 30 40]
print(v[::2])     # every 2nd element → [10 30 50]                   *IMPORTANT*
print(v[::-1])    # reverse → [60 50 40 30 20 10]                    *IMPORTANT*


# Now lets play with the 2D arrays
#let 3 * 3 matrix
print(arr[0:2, 1:3])  #First two rows, last two columns.             *IMPORTANT*

# rows 0-1, cols 1-2
# [[20 30]
#  [50 60]]


# Now we want to play by picking some elements from different indeces

v = np.array([10,20,30,40,50])
print(v[[2,3,0]])   # → [10 30 40]                                   *IMPORTANT*


# Now we want to play this game with the 2D arrays

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[[1,2],[0,2]])   # Picks arr[1,0] and arr[2,2]              *IMPORTANT*
                           # [40 90]


# whooo! Now we are going with the Boolean Indexing in numpy arrays

# one dimension array
num = np.array([10,20,30,40,50,60, 70,80,90,100])
print(num[num > 50])

# 2D array (Martrix)
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

arr[arr < 50] = 0  #we can replace  using condition                  *IMPORTANT*
print(arr)
# [[ 0  0 30]
#  [ 0 50 60]
#  [70 80 90]]



# <---------------------------------------------------------------------------->


#✅ Summary of Indexing & Slicing

# [row, col] → basic indexing.

# : → slicing (start:end:step).


# arr[:, i] → full column; arr[i, :] → full row.                     *IMPORTANT*

print(arr[:,1],arr[0,:])

# Fancy indexing → pick arbitrary elements.

# Boolean indexing → pick elements by condition.

# Views vs Copies → slicing is view, fancy/boolean indexing makes copy.           *IMPORTANT*


In [ ]:
# Difference between view and copy

# 1 ---- > Slicing gives a views -> changes affect original array.
# 2 -----> Fancy(multi picking elements) and Boolean indexing gives a copy


# <---------------------------------->                               *IMPORTANT*
# View (No new data, just a window)

arr = np.array([10, 20, 30, 40, 50])
sub = arr[1:4]    # slice = view
print("sub before:", sub)

sub[0] = 999      # change sub[0]
print("sub after:", sub)
print("original arr:", arr)

# <---------------------------------->                               *IMPORTANT*
#Copy (New data, independent)

arr = np.array([10, 20, 30, 40, 50])
copy = arr[[0, 2, 4]]   # fancy indexing → copy
print("copy before:", copy)

copy[0] = 777
print("copy after:", copy)
print("original arr:", arr)


# <---------------------------------->
# Lets do it with Matrices
# 1. View with Slicing (Submatrix shares memory)                     *IMPORTANT*

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Original Matrix A:\n", A)

sub = A[:2, :2]   # top-left 2x2 block                               *IMPORTANT*
print("Submatrix (view):\n", sub)

sub[0,0] = 999
print("Changed Submatrix:\n", sub)
print("Original Matrix A:\n", A)


#2. Copy with Fancy Indexing (Independent Matrix)


copy = A[[0,1], :2]   # pick rows 0,1 and cols 0,1 → copy            *IMPORTANT*
print("Copied Submatrix:\n", copy)

copy[0,0] = 111
print("Changed Copied Submatrix:\n", copy)
print("Original Matrix A:\n", A)


In [ ]:
#3️⃣ Mathematical Operations & Broadcasting in NumPy

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Addition
print(a + b)   # [11 22 33]

# Subtraction
print(a - b)   # [9 18 27]

# Multiplication
print(a * b)   # [10 40 90]

# Division
print(b / a)   # [10. 10. 10.]

# Power
print(a ** 2)  # [1 4 9]


arr = np.array([1, 4, 9, 16, 10])

print(np.sqrt(arr))   # [1. 2. 3. 4.]
print(np.exp(arr))    # e^arr
print(np.log(arr))    # ln(arr)
print(np.sin(arr))    # sin(arr)


# Broadcasting

# Definition: Applying an operation on arrays of different shapes.

# NumPy automatically “broadcasts” smaller array to match larger array’s shape.

# Rule 1: Shapes must be compatible → either same or one dimension = 1
arr = np.array([1, 4, 9, 16, 10])
new_val = 12

print (arr + new_val)

# lets do it for matrices
A = np.array([[3,6],[7,2]])
B = np.array([10,20])
print(A + B)

# Broadcasting with Column Vectors
C = np.array([[10],[20]])
print(A + C)

In [ ]:
#Aggregate Functions

arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

number_arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(number_arr.reshape(5,2))
print(number_arr.reshape(2,5))
print(number_arr.reshape(10,1))
print(number_arr.sum())
print(number_arr.mean())
print(number_arr.max())
print(number_arr.min())



# Axis Concept (Row vs Column)

# Axis = dimension number (like coordinate direction).

# axis=0 → operate down the rows (column-wise)

# axis=1 → operate across the columns (row-wise)


arr = np.array([[1, 7, 9],
       [4, 5, 6]])

print(arr.sum())         # Axis = 0 (Column-wise)
print(arr.sum(axis=0))              #Column 1: 1+4 = 5
print(arr.max(axis=0))              #Column 2: 2+5 = 7
print(arr.min(axis=0))              #Column 3: 3+6 = 9
print(arr.sum(axis=1))   # Axis = 1 (Row-wise)
print(arr.max(axis=1))              #Row 1: 1+2+3 = 6
print(arr.min(axis=1))              #Row 2: 4+5+6 = 15




# Other Aggregates

print(np.prod(arr))         # Product of all → 720   , sabhi elements ko multiply kar do.
print(np.std(arr))          # Standard deviation → ~1.707
print(np.var(arr))          # Variance → ~2.916
print(np.cumsum(arr))       # Cumulative sum (flattened)
print(np.cumprod(arr))      # Cumulative product (flattened)



In [ ]:
# Problem Discussion

# Problem 1

# Frequency of transitions between 3 states
freq = np.array([[5, 2, 3],
                 [1, 3, 6],
                 [4, 4, 2]])

print("Frequency matrix:\n", freq)

row_sum = freq.sum(axis=1)
print(row_sum)
A = row_sum.reshape(3,1)
print(A)
B = freq  / A
print(B.sum(axis=1))

# Sanjeev You rocked it !

# Problem 2

signal = np.array([5, -2, 3, 4, -1])
running_total = np.cumsum(signal)
print("Running total:", running_total)

# This question was very easy


In [ ]:
# Problem 3

data = np.array([10, 12, 9, 11, 10, 13])
#check
print(data.sum())
print(data.mean())
print(data.max())
print(data.min())
#logical method
sum = data.sum()
N = data.size
mean = sum / N
print(mean)
variation = data - mean
variation = variation ** 2
variation = variation.sum()
variation = variation / N
print(variation)
print(np.sqrt(variation))
#Direct solving method
print(data.var())
print(data.std())


In [ ]:
# 🌐 Linear Algebra Operations in NumPy (np.linalg)

#1 Dot product

a = np.array([1,2,3])
b = np.array([4,5,6])

prod = a * b
print(prod.sum()) #first logical method

print(np.dot(a,b))   # 1*4 + 2*5 + 3*6 = 32
print(a @ b)         # same


#2 Matrix Multiplication

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B)

# I am feeling very happy right now .... thank you numpy



#3 Transpose

A_transpose = A.T
print(A_transpose)
print(A.transpose())

#4 Determinant

print(np.linalg.det(A))
print(np.linalg.det(A_transpose))

#5 Inverse
A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)
print(np.linalg.inv(A))
print(np.linalg.inv(A_transpose))


print(A @ A_inverse)   # Identity matrix
print(B @ B_inverse)   # Identity matrix


In [ ]:
#             ***IMPORTANT DOUBT***

A = np.array([[1, 2], [3, 4]])
A_inverse = np.linalg.inv(A)

product = A @ A_inverse

# Round to nearest integer (or desired precision)
product_exact = np.round(product, decimals=0)

print(product)
print(product_exact)
#

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# Eigenvalues and Eigenvectors

A = np.array([[1,0],[0,2]])
vals,vacs = np.linalg.eig(A)
print("Eigenvalues:\n",vals)
print("Eigenvectors:\n",vacs)

In [ ]:
# Solve the system of linear equations

A = np.array([[1,5],[1,9]])
b = np.array([1,2])
x = np.linalg.solve(A,b)
round_x = np.round(x, decimals=2)
print(round_x)
print(x)
# verify answer
print(A @ x)


In [ ]:
# Problem based on linear equation

A = np.array([[2,1],[1,3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print("Solution:\n", x)
y = np.round(x , decimals=0)
print(y)

# verify answer
v = A @ x

# solve using A^−1 b
A_inv = np.linalg.inv(A)
print(A_inv @ b)

In [ ]:
# Practice what we have learned
import numpy as np

arr = np.array([1,2,3,4,5], dtype=np.float32)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

In [ ]:
# Question 2
M = np.array([[10,20,30],[40,50,60],[70,80,90]])
# print(M)
print(M[1,:])
print(M[:,2])
print(M[:2,:2])


In [ ]:
# Question 3

import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Addition
sum_ab = A + B
print("A + B:\n", sum_ab)

# Element-wise multiplication
elem_prod = A * B
print("Element-wise product:\n", elem_prod)

# Matrix multiplication
matrix_prod = A @ B
print("Matrix multiplication:\n", matrix_prod)

# Inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Check identity
print("A @ A_inv:\n", A @ A_inv)


In [ ]:
# problem 4

A = np.array([[2,1],[1,3]])
B = np.array([8,13])
x = np.linalg.solve(A,B)
print(x)
A_inv = np.linalg.inv(A)
print(A_inv @ B)
x_int = np.round(x, decimals=0)
print(x_int)

Hey ,today I have completed my three topics in numpy and Iam very happy with these things .

Now I am moving to the next chepter

In [ ]:
import numpy as np
arr_float = np.array([1.1, 2.5, 3.7,4],dtype=np.float32)
arr_int = arr_float.astype(int)
print(arr_int)  # [1 2 3]
print(arr_int.dtype)  # int32 (system dependent)


🌐 Universal Functions (ufuncs) in NumPy

---


A Universal Function (ufunc) in NumPy is a function that operates element-wise on ndarray objects.

They are implemented in C, so they run very fast.

They support broadcasting, type casting, and multiple inputs/outputs.

 ## 4.1 Mathematical Functions (ufuncs)

---



These are element-wise operations you can perform on arrays.

np.mod(a, b) performs element-wise modulo operation:

| a | b | a % b (mod) |
| - | - | ----------- |
| 2 | 1 | 2 % 1 = 0   |
| 4 | 2 | 4 % 2 = 0   |
| 6 | 3 | 6 % 3 = 0   |



In [ ]:
a = np.array([2,4,6])
b = np.array([1,2,3])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a, b))
print(np.power(a, 2))
print(np.power(b, 3))
print(np.mod(a, b))
print(np.mod(b, a))
print(np.mod(b, 2))
print(np.mod(b, 7))


# Combined / Multiple Operations

c = np.add(np.multiply(a,b),2)
print(c)

4.2 Trigonometric Functions (ufuncs)

Trigonometric ufuncs allow you to perform element-wise trigonometric calculations on arrays. Perfect for angles, waves, physics, graphics, rotations, etc.

1️⃣ Basic Trigonometric Function

| Function    | Description              |
| ----------- | ------------------------ |
| `np.sin(x)` | Sine of x (x in radians) |
| `np.cos(x)` | Cosine of x              |
| `np.tan(x)` | Tangent of x             |


In [ ]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi], dtype=np.float128)    #np.pi is NumPy’s constant for π (pi) → 3.141592653589793
print("sin:", np.round(np.sin(angles), decimals=0))  # [0. 1. 0.]
print("cos:", np.round(np.cos(angles), decimals=0))  # [1. 0. -1.]
print("tan:", np.round(np.tan(angles), decimals=0))  # [0. inf 0.] (tan(pi/2) → infinity)



2️⃣ Inverse Trigonometric Functions
| Function       | Description                    |
| -------------- | ------------------------------ |
| `np.arcsin(x)` | Inverse sine (returns radians) |
| `np.arccos(x)` | Inverse cosine                 |
| `np.arctan(x)` | Inverse tangent                |


In [ ]:
x = np.array([0,0.5,1])
print(np.arcsin(x))

[0.         0.52359878 1.57079633]


3️⃣ Degrees ↔ Radians Conversion

np.deg2rad → degrees to radians

np.rad2deg → radians to degrees

In [ ]:
x_rad = np.array([np.pi/6, np.pi/4 , np.pi/3])
x_deg = np.rad2deg(x_rad)
print(x_deg)
print(x_rad)
print(np.deg2rad(x_deg))
print(np.radians(x_deg))
print(np.sin(np.degrees(x_deg)))
print(np.round(np.sin(x_deg), decimals=0))
print(np.round(np.cos(x_deg), decimals=0))
print(np.round(np.tan(x_deg), decimals=0))
print(np.round(np.sin(x_rad), decimals=0))
print(np.round(np.cos(x_rad), decimals=0))
print(np.round(np.tan(x_rad), decimals=0))

4️⃣ Combined Example: Sine Wave

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10*np.pi, 1000)  # 5 points from 0 to 2pi
y = np.sin(x)

plt.plot(x,y)
plt.title('Sine Wave')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.show()

🌐 4.3 Exponential & Logarithmic Functions
\
1️⃣ Exponential Function: np.exp()

Calculates
𝑒
𝑥
 element-wise, where
𝑒
≈
2.71828
e≈2.71828

Syntax: np.exp(array)

In [ ]:
import numpy as np

a = np.array([0, 1, 2])
print(np.exp(a))  # [1.         2.71828183 7.3890561]


2️⃣ Natural Logarithm: np.log()

Calculates ln(x) → natural log (base e) element-wise

Syntax: np.log(array)

In [ ]:
a = np.array([1, np.e, np.e**2])
print(np.log(a))  # [0. 1. 2.]


3️⃣ Logarithm Base 10: np.log10()

In [ ]:
a = np.array([1, 10, 100, 1000])
print(np.log10(a))  # [0. 1. 2. 3.]


4️⃣ Logarithm Base 2: np.log2()

In [ ]:
a = np.array([1, 2, 4, 8])
print(np.log2(a))  # [0. 1. 2. 3.]


5️⃣ Combined Example

In [ ]:
# Suppose you invest $1000 at 5% interest compounded yearly for 3 years:
P = 1000
r = 0.05
t = 3

# Exponential growth formula: A = P * e^(r*t)
A = P * np.exp(r*t)
print("Amount after 3 years:", A)


## 🌐 4.4 Statistical Functions (NumPy Aggregates)


1️⃣ Mean

Average of all elements

Syntax: np.mean(array, axis=None)

 axis=0 → column-wise (for 2D array)

 axis=1 → row-wise



2️⃣ Median

Middle value when sorted

Syntax: np.median(array, axis=None)

3️⃣ Standard Deviation

Measures spread of data

Syntax: np.std(array, axis=None)

4️⃣ Variance

Square of standard deviation

Syntax: np.var(array, axis=None)

5️⃣ Min / Max

np.min(array) → smallest element

np.max(array) → largest element

6️⃣ Sum / Product

np.sum(array) → sum of elements

np.prod(array) → product of elements

7️⃣ Cumulative Sum / Product

np.cumsum(array) → cumulative sum

np.cumprod(array) → cumulative product

In [ ]:
data = np.linspace(0,18,6)
print(data)
print(np.mean(data))

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(np.mean(a))  # 3.0
print(np.median(a))  # 3
print(np.std(a))  # ~1.414
print(np.var(a))  # 2.0
print(np.min(a))  # 1
print(np.max(a))  # 5
print(np.sum(a))  # 15
print(np.prod(a))  # 120
print(np.cumsum(a))  # [1 3 6 10 15]
print(np.cumprod(a)) # [1 2 6 24 120]

In [ ]:
a = set({})
print(type(a))

<class 'set'>
